// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc4825.PlyBoy.subsystems;
import org.usfirst.frc4825.PlyBoy.RobotMap;
import org.usfirst.frc4825.PlyBoy.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class CompressorSubsystem1 extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Relay spike1 = RobotMap.compressorSubsystem1Spike1;
    DigitalInput digitalInput1 = RobotMap.compressorSubsystem1DigitalInput1;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMENT
        // Set the default command for a subsystem here.
        setDefaultCommand(new CompressorCommand1());
    }
    
    public boolean compressorOn(){
        return spike1.get() == Relay.Value.kForward;
    }
    
    public boolean atPressure(){
        return digitalInput1.get() == false;
    }
    
    public void turnOn(){
        spike1.set(Relay.Value.kForward);
    }
    
    public void turnOff(){
        spike1.set(Relay.Value.kOff);
    }
    
    
}
