// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc4825.MotorRelayExample.subsystems;

import org.usfirst.frc4825.MotorRelayExample.RobotMap;
import org.usfirst.frc4825.MotorRelayExample.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class MotorRelay extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Relay motorRelaySpike = RobotMap.motorRelayMotorRelaySpike;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    boolean motorInForward = false;
    public boolean isMotorInForward()
    {
        return motorInForward;
    }

    public void putMotorInForward()
    {
        if( isMotorInForward() )
            return;
        motorRelaySpike.set(Relay.Value.kForward);
        motorInForward = true;
    }
 
    public void stopMotor()
    {
        motorRelaySpike.set(Relay.Value.kOff);
        motorInForward = false;
    }
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
}

