// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc4825.AshburySubsystemRobot.subsystems;
import org.usfirst.frc4825.AshburySubsystemRobot.RobotMap;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import org.usfirst.frc4825.AshburySubsystemRobot.Robot;
import org.usfirst.frc4825.AshburySubsystemRobot.Robot_InstanceField;
import org.usfirst.frc4825.AshburySubsystemRobot.Support.MotorDirectionType;
/**
 *
 */
public class Launcher extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController launcherMotor1 = RobotMap.launcherLauncherMotor1;
    SpeedController launcherMotor2 = RobotMap.launcherLauncherMotor2;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    private boolean isMotorOn = false;
    private Timer spinUpTimer = new Timer();
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    public void turnOnLauncher( double percentage1, double percentage2 )
    {
        double direction = 1.0;
        MotorDirectionType directionType = (MotorDirectionType)Robot.oi.reverseModeChooser.getSelected();
            
        if( directionType == MotorDirectionType.FORWARD_DIRECTION ) {
            direction = 1.0;
        }
        else if (directionType == MotorDirectionType.REVERSE_DIRECTION ) {
            direction = -1.0;
        }
        //launcher 1 motor has to be inverted...
        launcherMotor1.set(-1*direction*percentage1);
        launcherMotor2.set(-1*direction*percentage2);
        isMotorOn = true;
        spinUpTimer.start();
    }
    public void turnOffLauncher()
    {
        launcherMotor1.set(0.0);
        launcherMotor2.set(0.0);
        isMotorOn = false;
        spinUpTimer.reset();
        spinUpTimer.stop();
    }
    public boolean isMotorOn()
    {
        return isMotorOn;
    }
    
    public boolean isMotorAtSpeed()
    {
        if( isMotorOn() && spinUpTimer.get() > Robot_InstanceField.getLauncherSpinUpTime() ) {
            return true;
        }
        else {
            return false;
        }
    }
    
}
