// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4825.FRC_2014.commands;

import org.usfirst.frc4825.FRC_2014.Support.UserMessagePrinter;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4825.FRC_2014.Robot;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class astralcmd extends CommandGroup {

    public astralcmd() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        addSequential(new DriveForward());
        addSequential(new Wait());
        addSequential(new DriveBackwards());
        addSequential(new Wait());
        addSequential(new DriveForward());
    }
}
