package org.usfirst.frc4825.FRC_2014.commands;
import org.usfirst.frc4825.FRC_2014.Support.UserMessagePrinter;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4825.FRC_2014.Robot;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
/**
 *
 */
public class driveForwardWithoutSensors2 extends Command {
    //drives forward on timeout
    public driveForwardWithoutSensors2(){
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        System.out.println("Initilize driveForwardWithoutSensors2");
        setTimeout(SmartDashboard.getNumber("Time of driving forward2"));
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        Robot.driveTrain.DriveForwardNoSens();
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return isTimedOut();
    }
    // Called once after isFinished returns true
    protected void end() {
        Robot.driveTrain.stop();
        System.out.println("End driveForwardWithoutSensors2");
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
        System.out.println("driveForwardWithoutSensors2 interrupted");
    }
}